import type { Metadata } from 'next';
import { NextAuthProvider } from './components/providers/NextAuthProvider';
import { Poppins } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';
import { Header } from '@/components/Header';
import Footer from '@/components/Footer';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='light' className='light'>
      <NextAuthProvider>
        <body
          className={`${poppins.variable} antialiased min-h-screen flex flex-col `}
        >
          <Header />
          <main className=' flex-grow px-8'>{children}</main>
          <Footer />
          <Toaster />
        </body>
      </NextAuthProvider>
    </html>
  );
}
